package com.nvcomputerclub.nvextras.nvextrasapp;

import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.TextView;

public class DetailActivity extends ActionBarActivity {


    //Textview objects in xml file
    TextView title, detail;
    //String arrays to create Club Object
    String[] clubList;
    String[] clubDetails;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_detail);

        //Initialize string arrays from array values file-
        clubList = getApplicationContext().getResources().getStringArray(R.array.club_names);
        clubDetails = getApplicationContext().getResources().getStringArray(R.array.club_details);

        //Initiallize textview objects
        title = (TextView) findViewById(R.id.titleText);
        detail = (TextView) findViewById(R.id.detailText);

        //initialize intent object to recieve information passed from MainActivity
        Intent i = getIntent();
        int positionClicked = i.getIntExtra(MainActivity.EXTRA_POSITION, 0);

        //Create new Club object
        Club club = new Club(positionClicked, clubList, clubDetails);
        //Fill the textviews of the xml file with the necessary text from the Club object's fields
        club.setAll(title, detail);
        //Set activity's title (The Black bar at top of screen but below part with battery) to the name of the Club
        setTitle(club.getTitle() + " Info");


    }


    //Menu code that can be used later-autogenerated
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_detail, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
